#!/bin/sh
LCORE="../lcore"
COMMONOPTS="-Fu${LCORE} -Fi${LCORE} -Sd -XX"
FPC="fpc"
./clean
$FPC $COMMONOPTS bcreationdate.dpr
./bcreationdate
$FPC $COMMONOPTS -dnomodeless bircd.dpr
brandelf -t Linux bircd
$FPC $COMMONOPTS mkpasswd.pas
brandelf -t Linux mkpasswd
